/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lldjrzokpsjeivlyjahu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsZGpyem9rcHNqZWl2bHlqYWh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTA5OTAsImV4cCI6MjA3MzUyNjk5MH0.-i3hW6JsLA-5GHb0FZ9zERdVoWpppz-tWcC1NlzFOvw"